### ISSUE TITLE
Add to the organisation

### ISSUE THREAD

**Issue by ShubhraSuman** [All-Time-Learners/General#2]
Linkedin: https://www.linkedin.com/in/shubhra-suman-3125a5135/
Twitter: https://twitter.com/ShubhraSuman5?t=8h7sidGdicTBpWsFfiHw7A&s=09

**Comment by aparna2071** [comment]
Hi, thanks for showing interest in this project ❤️
I have sent you an invite to join, kindly accept it 👍

**Comment by aparna2071** [comment]
Hi Shubhra, kindly change your visibility from private to public by going to People in this repo.
By changing to public only, this organisation will be visible to others on your github profile.
![12344](https://user-images.githubusercontent.com/54634804/190586889-b74dd0d1-6b12-4aa5-b831-b0d2f2c34f15.PNG)

**Comment by ShubhraSuman** [comment]
Done. Thanks
