### ISSUE TITLE
Add DellaDominic to the organization

### ISSUE THREAD

**Issue by DellaDominic** [All-Time-Learners/General#4]
LinkedIn - https://www.linkedin.com/in/de11ad0minic1

Great initiative @aparna2071 and @paraggaikwad11 ! Excited and looking forward to joining! 😀

**Comment by aparna2071** [comment]
Hi, thanks for showing interest in this repo ❤️
I have sent you an invite to join, kindly accept it 👍

We are also excited to collaborate more with all ❤️ 
Keep learning & growing 
Have a nice day Della 😍
